tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y gettext-base
      docker-compose pull
    command: |
      if [ ! -f .env ]; then
        cp .env.example .env
      fi
      echo "NIFI_KEYSTORE_PASSWORD=${NIFI_KEYSTORE_PASSWORD}" >> .env
      echo "NIFI_KEY_PASSWORD=${NIFI_KEY_PASSWORD}" >> .env
      echo "NIFI_TRUSTSTORE_PASSWORD=${NIFI_TRUSTSTORE_PASSWORD}" >> .env
      export NIFI_WEB_HTTPS_HOST=$(gp url ${NIFI_WEB_HTTPS_PORT} | cut -d'/' -f3)
      envsubst < ./nifi/conf/nifi.properties.template > ./nifi/conf/nifi.properties
      sudo chown -R 1000:1000 ./nifi
      sudo chmod -R 755 ./nifi
      sudo chown 1000:1000 ./nifi/conf/bootstrap.conf
      sudo chmod 644 ./nifi/conf/bootstrap.conf
      docker-compose up

ports:
  - port: 8443
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker