tasks:
  - init: |
      mkdir -p ./nifi/conf
      if [ ! -f ./nifi/conf/nifi.properties ]; then
        echo "nifi.web.https.port=\${NIFI_WEB_HTTPS_PORT}" > ./nifi/conf/nifi.properties
        echo "nifi.web.https.host=\${NIFI_WEB_HTTPS_HOST}" >> ./nifi/conf/nifi.properties
        echo "nifi.security.user.login.identity.provider=single-user-provider" >> ./nifi/conf/nifi.properties
        echo "nifi.security.user.authorizer=single-user-authorizer" >> ./nifi/conf/nifi.properties
      fi
      docker-compose pull
    command: |
      export NIFI_WEB_HTTPS_HOST=$(gp url ${NIFI_WEB_HTTPS_PORT} | cut -d'/' -f3)
      docker-compose up