tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y gettext-base
      docker-compose pull
    command: |
      if [ ! -f .env ]; then
        cp .env.example .env
      fi
      export NIFI_WEB_HTTPS_HOST=$(gp url ${NIFI_WEB_HTTPS_PORT} | cut -d'/' -f3)
      envsubst < ./nifi/conf/nifi.properties.template > ./nifi/conf/nifi.properties
      docker-compose up

ports:
  - port: 8443
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker