tasks:
  - init: docker-compose pull
    command: |
      if [ ! -f .env ]; then
        echo "NIFI_WEB_HTTPS_PORT=${NIFI_WEB_HTTPS_PORT}" > .env
        echo "NIFI_USERNAME=${NIFI_USERNAME}" >> .env
        echo "NIFI_PASSWORD=${NIFI_PASSWORD}" >> .env
      fi
      export NIFI_WEB_HTTPS_HOST=$(gp url ${NIFI_WEB_HTTPS_PORT} | cut -d'/' -f3)
      if [ ! -f ./nifi/conf/nifi.properties ]; then
        cp ./nifi/conf/nifi.properties.template ./nifi/conf/nifi.properties
      fi
      envsubst < ./nifi/conf/nifi.properties.template > ./nifi/conf/nifi.properties
      docker-compose up

ports:
  - port: 8443
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker