version: '3'
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "${NIFI_WEB_HTTPS_PORT}:${NIFI_WEB_HTTPS_PORT}"
    environment:
      - NIFI_WEB_HTTPS_PORT=${NIFI_WEB_HTTPS_PORT}
      - NIFI_WEB_HTTPS_HOST=${NIFI_WEB_HTTPS_HOST}
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_KEYSTORE_PASSWORD=${NIFI_KEYSTORE_PASSWORD}
      - NIFI_KEY_PASSWORD=${NIFI_KEY_PASSWORD}
      - NIFI_TRUSTSTORE_PASSWORD=${NIFI_TRUSTSTORE_PASSWORD}
    volumes:
      - ./nifi/conf:/opt/nifi/nifi-current/conf
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/state:/opt/nifi/nifi-current/state
      